import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '../_components/layouts/Header'
import Footer from '../_components/layouts/Footer'
import ToasterApp from '../_components/ui/toast'
import { Suspense } from 'react'
import { NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import { locales } from '@/i18n.config'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Base Next',
  description: 'Generated by create next app'
}

export function generateStaticParams() {
  return locales.map(locale => ({ locales: locale }))
}

export default async function LocalesLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{ locales: string }>

}) {
  const { locales: currentLocale } = await params

  // Validate the locale
  if (!locales.includes(currentLocale as any)) {
    notFound()
  }

  let messages
  try {
    messages = (await import(`../../messages/${currentLocale}.json`)).default
  } catch (error) {
    console.error('Failed to load messages:', error)
    notFound()
  }

  return (
    <html lang={currentLocale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <NextIntlClientProvider locale={currentLocale} messages={messages}>
          <Header />
          <Suspense fallback={<>loading...</>}>
            <main className='flex-grow'>{children}</main>
          </Suspense>
          <Footer />
          <ToasterApp />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
