import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Suspense } from "react";
import Footer from "./_components/layouts/Footer";
import ToasterApp from "./_components/ui/toast";
import Header from "./_components/layouts/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Base Next",
  description: "Generated by create next app",
};

export default async function LocalesLayout({
  children,
}: {
  children: React.ReactNode;
  params: Promise<{ locales: string }>;
}) {
  return (
    <html lang={"en"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <Suspense fallback={<>loading...</>}>
          <main className="flex-grow">{children}</main>
        </Suspense>
        <Footer />
        <ToasterApp />
      </body>
    </html>
  );
}
